import type { Metadata } from "next";

import CursorWrapper from "@/components/cursor-wrapper";
import { AProviders } from "@/components/providers/apollo-provider";
import { StoreProvider } from "@/components/providers/store-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`w-full max-w-screen h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CursorWrapper>
            <main
              className={`bg-linear-to-b from-blue-300  to-orange-100  dark:from-black  dark:to-gray-800 cursor-default`}
            >
              <StoreProvider>
                <AProviders>{children}</AProviders>
              </StoreProvider>
            </main>
          </CursorWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
