// PublicLayout.tsx
import DevFooter from "@/components/devFooter";
import FloatingWidget from "@/components/floating-widget";
import NavBar from "@/components/navBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shifaul Islam",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex flex-col w-full h-screen snap-y snap-mandatory overflow-y-auto scroll-smooth scrollbar-none">
      <NavBar className="sticky top-0 z-50 backdrop-blur-md" />
      <main className="flex-1 snap-y snap-mandatory">{children}</main>
      <DevFooter className="sticky bottom-0 z-50 backdrop-blur-md" />
      {/* Floating Widget */}
      <FloatingWidget />
    </div>
  );
}
